-- NUSANTARA BATIK
-- Struktur backend mengikuti tabel toko di WEBSITE_WARIH.
create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null, slug text not null unique, image text default '',
  description text default '', created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null, category text not null,
  price numeric(12,2) not null default 0 check (price >= 0),
  description text default '', sizes text[] not null default '{}',
  stock integer not null default 0 check (stock >= 0),
  image text default '', featured boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text default '', role text not null default 'customer'
    check (role in ('admin','customer')), created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null, phone text not null, address text not null,
  total numeric(12,2) not null default 0 check (total >= 0),
  status text not null default 'pending'
    check (status in ('pending','confirmed','processing','shipped','completed','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null, price numeric(12,2) not null default 0,
  size text not null, quantity integer not null default 1 check (quantity > 0), image text default ''
);

insert into public.categories(name,slug,description) values
('Batik Tulis','batik-tulis','Batik tulis dengan karakter motif yang kaya.'),
('Batik Cap','batik-cap','Batik cap dengan pola klasik dan modern.'),
('Kemeja Batik','kemeja-batik','Kemeja batik untuk acara formal maupun santai.'),
('Outer Batik','outer-batik','Outer dan layering dengan sentuhan motif Nusantara.'),
('Batik Casual','batik-casual','Batik harian dengan potongan kontemporer.')
on conflict(slug) do nothing;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

grant select on public.categories to anon,authenticated;
grant select on public.products to anon,authenticated;
grant select on public.profiles to authenticated;
grant select,insert,update,delete on public.products to authenticated;
grant select,insert on public.orders to anon,authenticated;
grant select,insert on public.order_items to anon,authenticated;
grant update on public.orders to authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories" on public.categories for select to anon,authenticated using(true);

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products" on public.products for select to anon,authenticated using(true);

drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile" on public.profiles for select to authenticated using(id=auth.uid());

drop policy if exists "Customers create orders" on public.orders;
create policy "Customers create orders" on public.orders for insert to anon,authenticated with check(true);

drop policy if exists "Admins read orders" on public.orders;
create policy "Admins read orders" on public.orders for select to authenticated
using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "Admins update orders" on public.orders;
create policy "Admins update orders" on public.orders for update to authenticated
using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "Customers create order items" on public.order_items;
create policy "Customers create order items" on public.order_items for insert to anon,authenticated with check(true);

drop policy if exists "Admins read order items" on public.order_items;
create policy "Admins read order items" on public.order_items for select to authenticated
using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products" on public.products for all to authenticated
using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

insert into storage.buckets(id,name,public) values('product-images','product-images',true)
on conflict(id) do update set public=true;

drop policy if exists "Public read product images" on storage.objects;
create policy "Public read product images" on storage.objects for select to public using(bucket_id='product-images');

drop policy if exists "Admins upload product images" on storage.objects;
create policy "Admins upload product images" on storage.objects for insert to authenticated
with check(bucket_id='product-images' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "Admins update product images" on storage.objects;
create policy "Admins update product images" on storage.objects for update to authenticated
using(bucket_id='product-images' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "Admins delete product images" on storage.objects;
create policy "Admins delete product images" on storage.objects for delete to authenticated
using(bucket_id='product-images' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Setelah user admin dibuat di Authentication > Users:
-- insert into public.profiles(id,full_name,role)
-- values('UUID-USER','Admin Nusantara Batik','admin')
-- on conflict(id) do update set role='admin';
