import { useEffect,useState } from "react";
import { useAuth } from "../context/AuthContext";
import { supabase } from "../lib/supabase";
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n||0);
export default function AdminDashboard(){
 const {profile,logout}=useAuth();const [products,setProducts]=useState([]),[orders,setOrders]=useState([]),[form,setForm]=useState({name:"",category:"Batik",price:"",description:"",sizes:"S,M,L,XL",stock:"0",image:"",featured:false}),[edit,setEdit]=useState(null),[msg,setMsg]=useState("");
 async function load(){const [p,o]=await Promise.all([supabase.from("products").select("*").order("created_at",{ascending:false}),supabase.from("orders").select("*").order("created_at",{ascending:false})]);setProducts(p.data||[]);setOrders(o.data||[])}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setMsg("Menyimpan...");const payload={...form,price:Number(form.price||0),stock:Number(form.stock||0),sizes:form.sizes.split(",").map(x=>x.trim()).filter(Boolean)};let r;if(edit)r=await supabase.from("products").update(payload).eq("id",edit);else r=await supabase.from("products").insert(payload);if(r.error)setMsg(r.error.message);else{setMsg("Produk tersimpan.");setForm({name:"",category:"Batik",price:"",description:"",sizes:"S,M,L,XL",stock:"0",image:"",featured:false});setEdit(null);load()}}
 async function del(id){if(!confirm("Hapus produk ini?"))return;await supabase.from("products").delete().eq("id",id);load()}
 if(profile?.role!=="admin")return <main className="admin-denied"><h1>Akses admin diperlukan.</h1><button className="button dark" onClick={logout}>Keluar</button></main>;
 return <main className="admin"><div className="admin-head"><div><span className="eyebrow">NUSANTARA BATIK</span><h1>Dashboard</h1></div><button onClick={logout}>Keluar</button></div><div className="admin-stats"><div><span>Produk</span><b>{products.length}</b></div><div><span>Pesanan</span><b>{orders.length}</b></div><div><span>Penjualan</span><b>{money(orders.filter(x=>x.status!=="cancelled").reduce((n,x)=>n+Number(x.total||0),0))}</b></div></div><div className="admin-grid"><form className="admin-form" onSubmit={save}><h2>{edit?"Edit produk":"Tambah produk"}</h2>{msg&&<div className="notice">{msg}</div>}<input placeholder="Nama produk" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Kategori" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input type="number" placeholder="Harga" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="Ukuran: S,M,L,XL" value={form.sizes} onChange={e=>setForm({...form,sizes:e.target.value})}/><input type="number" placeholder="Stok" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input placeholder="URL gambar Supabase" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><textarea rows="5" placeholder="Deskripsi" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Produk pilihan</label><button className="button dark wide">{edit?"Simpan perubahan":"Tambah produk"}</button></form><div className="admin-products"><h2>Produk</h2>{products.map(p=><div className="admin-product" key={p.id}><img src={p.image||p.image_url}/><div><b>{p.name}</b><span>{p.category} • {money(p.price)}</span></div><button onClick={()=>{setEdit(p.id);setForm({...p,sizes:Array.isArray(p.sizes)?p.sizes.join(","):p.sizes||""})}}>Edit</button><button onClick={()=>del(p.id)}>Hapus</button></div>)}</div></div></main>
}